### PR TITLE
Small Improvement for vNext's ReactiveProperty

### PR DESCRIPTION
**Pull request by neuecc**
vNext's perf improvement project is very good!
I make more some improvement.

* Validation is not always needed so all validation property change to `Lazy<T>`.
* `Observable.Never.Subscribe` in some ReactiveProperty constructors is no needed, remove it.
* Equals is maybe not valid, replace to `EqualityComparer<T>.Default.Equals`.
* `Observable.Merge` is slightly heavy, we can replace `Observable.StartWith` or call `OnNext` directly. I choose call directly in `ReactiveProperty.Subscribe`.

### CODE REVIEW

**Comment by xin9le** [comment]
[LGTM](http://lgtm.in/i/OeE1)

**Comment by TaviTruman** [comment]
This is great news guys; are you building libraries with 4.6.x binaries?

**Comment by runceel** [comment]
@TaviTruman OK. I released the v2.3-pre3 package.
This package includes .NET4.6 binaries.

Please try it.

**Comment by TaviTruman** [comment]
Okay, I'm giving it a try now.

**Comment by TaviTruman** [comment]
Okay guys I have tried to build one of my products with 2.3 pre3 package and I'm getting the following:

C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3274: The primary reference "ReactiveProperty.NET46, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.6.1" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6".

I looks like we got upgraded to .NET 4.6.1 with the latest Updates to Visual Studio and update to the Azure SDK. Our services use Azure Service Fabric so we must keep up with advances in that area thus the upgrade to 4.6.1; our WPF Aps are marked and set to use .NET Framework 4.6.

We are also getting these messages in our Blend and WPF Designers:

Some XAML Code:

UserControl x:Name="ProgramInfoUserControl" 
             x:Class="IKW.Contropolus.VKMC.UI.ProgramInfo.Module.Views.ProgramInfoView"
             DataContext="{Binding}"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:igDP="http://infragistics.com/DataPresenter" 
             xmlns:prism="http://www.codeplex.com/prism"
             xmlns:regions="http://www.codeplex.com/CompositeWPF"
             xmlns:coreInteractivity ="clr-namespace:System.Windows.Interactivity;assembly=System.Windows.Interactivity"
             xmlns:reactiveProperty="clr-namespace:Reactive.Bindings.Interactivity;assembly=ReactiveProperty.NET46"
             xmlns:uiRegionNames="clr-namespace:IKW.Contropolus.WPF.UI.Infrastructure.UI.RegionNames;assembly=IKW.Contropolus.WPF.UI.Infrastructure">

    

    <UserControl.Resources>
        <Style x:Key="ProgramShortDescStyle" TargetType="{x:Type igDP:CellValuePresenter}">
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="{x:Type igDP:CellValuePresenter}">
                        <Grid Width="{TemplateBinding Width}" Height="{TemplateBinding Height}">
                            <TextBlock Width="Auto"
                                       Height="Auto"
                                       Margin="{TemplateBinding Padding}"
                                       Text="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=Value}"
                                       TextBlock.LineStackingStrategy="BlockLineHeight"
                                       TextTrimming="None"
                                       TextBlock.HorizontalAlignment="Stretch"
                                       TextBlock.TextAlignment="Left"
                                       TextWrapping="Wrap" />
                        </Grid>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
    </UserControl.Resources>

    

    

    

    <Grid x:Name="UIGridLayoutRoot">
        
        

        <igDP:XamDataCards x:Name="UIProgramInfoData"
                           DataSource="{Binding ProgramInfoView}"
                           Theme="IGTheme"
                           HorizontalContentAlignment="Left" 
                           VerticalContentAlignment="Top">

            <igDP:XamDataCards.FieldLayoutSettings>
                <igDP:FieldLayoutSettings FieldResizingArea="LabelsAndCells" />
            </igDP:XamDataCards.FieldLayoutSettings>

            <igDP:XamDataCards.FieldSettings>
                <igDP:FieldSettings AllowCellVirtualization="False"
                                    AllowEdit="False"
                                    LabelTextAlignment="Left"
                                    LabelTextTrimming="CharacterEllipsis"
                                    LabelTextWrapping="WrapWithOverflow" 
                                    DataItemUpdateTrigger="OnCellValueChange" />
            </igDP:XamDataCards.FieldSettings>

            <igDP:XamDataCards.ViewSettings>
                <igDP:CardViewSettings AllowCardHeightResizing="True"
                                       AllowCardWidthResizing="True"                                       
                                       CollapseEmptyCellsButtonVisibility="Visible"
                                       Orientation="Horizontal"
                                       Padding="4,2,4,2"
                                       ShouldCollapseEmptyCells="True" 
                                       AutoFitCards="Horizontally"/>
            </igDP:XamDataCards.ViewSettings>
        </igDP:XamDataCards>

        <coreInteractivity:Interaction.Triggers>

            <coreInteractivity:EventTrigger 
                    x:Name="DataCardIsLoaded"
                    EventName="Loaded" 
                    SourceName="UIProgramInfoData">

                <reactiveProperty:EventToReactiveProperty
                        x:Name="ReactOnLoaded" 
                        ReactiveProperty="{Binding ReactOnLoaded, UpdateSourceTrigger=PropertyChanged}" />

            </coreInteractivity:EventTrigger>

            <coreInteractivity:EventTrigger 
                    x:Name="FieldLayoutReactor"
                    EventName="FieldLayoutInitialized"
                    SourceName="UIProgramInfoData">

                <reactiveProperty:EventToReactiveProperty 
                        x:Name="ReactOnInitialized"
                        IgnoreEventArgs="False"
                        ReactiveProperty="{Binding ReactOnInitialized, UpdateSourceTrigger=PropertyChanged}" />

            </coreInteractivity:EventTrigger>

        </coreInteractivity:Interaction.Triggers>

    </Grid>
</UserControl>


ERROR MESSAGE/BUILD ERRORS:

**Comment by runceel** [comment]
@TaviTruman Thank you for your feedback.
I retarget .NET Framework 4.6. And rebuild and release the pre4 package.

I tested this code.

```cs
using Reactive.Bindings;
using Reactive.Bindings.Interactivity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Reactive.Linq;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace WpfApplication5
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }
    }

    public class MainWindowViewModel
    {
        public ReactiveProperty<string> IO { get; } = new ReactiveProperty<string>();
    }

    public class SampleConverter : ReactiveConverter<object, string>
    {
        protected override IObservable<string> OnConvert(IObservable<object> source)
        {
            return source.Select(_ => DateTime.Now.ToString());
        }
    }
}
```

```xml
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApplication5"
        xmlns:i="http://schemas.microsoft.com/expression/2010/interactivity"
        xmlns:Interactivity="clr-namespace:Reactive.Bindings.Interactivity;assembly=ReactiveProperty.NET46"
        x:Class="WpfApplication5.MainWindow"
        mc:Ignorable="d"
        Title="MainWindow"
        Height="350"
        Width="525">
    <Window.DataContext>
        <local:MainWindowViewModel />
    </Window.DataContext>
    <StackPanel>
        <Button Content="Click">
            <i:Interaction.Triggers>
                <i:EventTrigger EventName="Click">
                    <Interactivity:EventToReactiveProperty ReactiveProperty="{Binding IO, Mode=OneWay}">
                        <local:SampleConverter />
                    </Interactivity:EventToReactiveProperty>
                </i:EventTrigger>
            </i:Interaction.Triggers>
        </Button>
        <TextBlock Text="{Binding IO.Value}" />
    </StackPanel>
</Window>
```
No compile and design time error.

**Comment by TaviTruman** [comment]
Perfect and thank you; this code you supplied, it works for me now too! Let me apply it to one other of my projects. I'll get back to you later on today with and update and close out this issue.

**Comment by TaviTruman** [comment]
Still getting a miss-matching error in the Visual Studio Designer and in Blend; here is the sample offending XAML code:

<UserControl
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:prism="http://www.codeplex.com/prism"
             xmlns:regions="http://www.codeplex.com/CompositeWPF"
             xmlns:coreInteractivity ="http://schemas.microsoft.com/expression/2010/interactivity"
             xmlns:reactiveProperty="clr-namespace:Reactive.Bindings.Interactivity;assembly=ReactiveProperty.NET46"
             xmlns:uiRegionNames="clr-namespace:IKW.Contropolus.WPF.UI.Infrastructure.UI.RegionNames;assembly=IKW.Contropolus.WPF.UI.Infrastructure"
             xmlns:ig="http://schemas.infragistics.com/xaml" 
             x:Name="MainMenuControl" 
             x:Class="IKW.Contropolus.VKMC.UI.MainMenu.Module.Views.MainMenuView"
             mc:Ignorable="d">

    <UserControl.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </UserControl.Resources>

    <Grid x:Name="ControlHost">
        <ig:XamMenu x:Name="MainMenuController">

            <coreInteractivity:Interaction.Triggers>
                  
                
                <coreInteractivity:EventTrigger EventName="Click" SourceName="OpenAboutShell">
                    <reactiveProperty:EventToReactiveProperty ReactiveProperty="{Binding OpenAboutShellClickEvent, UpdateSourceTrigger=PropertyChanged}"/>
                </coreInteractivity:EventTrigger>
                <coreInteractivity:EventTrigger EventName="Click" SourceName="CloseAboutShell">
                    <reactiveProperty:EventToReactiveProperty ReactiveProperty="{Binding CloseAboutShellClickEvent, UpdateSourceTrigger=PropertyChanged}"/>
                </coreInteractivity:EventTrigger>
                <coreInteractivity:EventTrigger EventName="Click" SourceName="CloseAllAboutShells">
                    <reactiveProperty:EventToReactiveProperty ReactiveProperty="{Binding CloseAllAboutShellClickEvent, UpdateSourceTrigger=PropertyChanged}"/>
                </coreInteractivity:EventTrigger>
                <coreInteractivity:EventTrigger EventName="Click" SourceName="ReloadAboutShellMenuControl">
                    <reactiveProperty:EventToReactiveProperty ReactiveProperty="{Binding ReloadAboutShellMenuControlClickEvent, UpdateSourceTrigger=PropertyChanged}"/>
                </coreInteractivity:EventTrigger>

                  

                <coreInteractivity:EventTrigger EventName="Click" SourceName="OpenWorkflowControlShell">
                    <reactiveProperty:EventToReactiveProperty ReactiveProperty="{Binding OpenWorkflowControlClickEvent, UpdateSourceTrigger=PropertyChanged}"/>
                </coreInteractivity:EventTrigger>
                <coreInteractivity:EventTrigger EventName="Click" SourceName="CloseWorkflowControlShell">
                    <reactiveProperty:EventToReactiveProperty ReactiveProperty="{Binding CloseWorkflowControlClickEvent, UpdateSourceTrigger=PropertyChanged}"/>
                </coreInteractivity:EventTrigger>

                  

                <coreInteractivity:EventTrigger EventName="Click" SourceName="OpenWorkflowDisplayMonitorShell">
                    <reactiveProperty:EventToReactiveProperty ReactiveProperty="{Binding OpenWorkflowDisplayMonitorEvent, UpdateSourceTrigger=PropertyChanged}"/>
                </coreInteractivity:EventTrigger>
                <coreInteractivity:EventTrigger EventName="Click" SourceName="CloseWorkflowDisplayMonitorShell">
                    <reactiveProperty:EventToReactiveProperty ReactiveProperty="{Binding CloseWorkflowDisplayMonitorClickEvent, UpdateSourceTrigger=PropertyChanged}"/>
                </coreInteractivity:EventTrigger>
            </coreInteractivity:Interaction.Triggers>

            <ig:XamMenuItem x:Name="AboutShellMenu" Header="Load About Shell">
                <ig:XamMenuItem x:Name="OpenAboutShell" Header="Open About Shell" />
                <ig:XamMenuItem x:Name="CloseAboutShell" Header="Close About Shell" />
                <ig:XamMenuItem x:Name="CloseAllAboutShells" Header="Close About Shell Stack" />
                <ig:XamMenuItem x:Name="ReloadAboutShellMenuControl" Header="Reload About Shell Menu Control" />
            </ig:XamMenuItem>
            
            <ig:XamMenuItem x:Name="WorkflowControlMenu" Header="Load Workflow Control Shell">
                <ig:XamMenuItem x:Name="OpenWorkflowControlShell" Header="Open Workflow Control Shell" />
                <ig:XamMenuItem x:Name="CloseWorkflowControlShell" Header="Close Workflow Control Shell" />
            </ig:XamMenuItem>
            
            <ig:XamMenuItem x:Name="WorkflowDisplayMonitorMenu" Header="Load Workflow Display Monitor Shell">
                <ig:XamMenuItem x:Name="OpenWorkflowDisplayMonitorShell" Header="Open Workflow Display Monitor Shell" />
                <ig:XamMenuItem x:Name="CloseWorkflowDisplayMonitorShell" Header="Close Workflow Display Monitor Shell" />
            </ig:XamMenuItem>
            
        </ig:XamMenu>
    </Grid>
</UserControl>

Not sure what exactly the compiler is complaining about as  the program compiles and runs without error. The problem is that the error crashes and Designers.

**Comment by runceel** [comment]
fm...

You can works simple project?
But you can't production code?

I will try your code snippet. (After Infragistics install) Please wait.

**Comment by runceel** [comment]
I tryed. But I can't reproduced.

I write this xaml.

```xml
<UserControl x:Class="WpfApplication1.UserControl1"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:prism="http://www.codeplex.com/prism"
             xmlns:regions="http://www.codeplex.com/CompositeWPF"
             xmlns:coreInteractivity="http://schemas.microsoft.com/expression/2010/interactivity"
             xmlns:reactiveProperty="clr-namespace:Reactive.Bindings.Interactivity;assembly=ReactiveProperty.NET46"
             xmlns:ig="http://schemas.infragistics.com/xaml"
             xmlns:local="clr-namespace:WpfApplication1"
             mc:Ignorable="d"
             d:DesignHeight="300"
             d:DesignWidth="300">
    <UserControl.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <!--<ResourceDictionary Source="/IGMenu;component/Assets/Global.xaml" />
            <ResourceDictionary Source="/Infragistics.Themes.IGTheme;component/IG.xamMenu.xaml" />
            <ResourceDictionary Source="/IGMenu;component/Assets/MenuDataTemplate.xaml"/>-->
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </UserControl.Resources>

    <Grid x:Name="ControlHost">
        <ig:XamMenu x:Name="MainMenuController">

            <coreInteractivity:Interaction.Triggers>
                <!--Interactive Event Triggers for the About Shell-->

                <coreInteractivity:EventTrigger EventName="Click"
                                                SourceName="OpenAboutShell">
                    <reactiveProperty:EventToReactiveProperty ReactiveProperty="{Binding OpenAboutShellClickEvent, UpdateSourceTrigger=PropertyChanged}" />
                </coreInteractivity:EventTrigger>
                <coreInteractivity:EventTrigger EventName="Click"
                                                SourceName="CloseAboutShell">
                    <reactiveProperty:EventToReactiveProperty ReactiveProperty="{Binding CloseAboutShellClickEvent, UpdateSourceTrigger=PropertyChanged}" />
                </coreInteractivity:EventTrigger>
                <coreInteractivity:EventTrigger EventName="Click"
                                                SourceName="CloseAllAboutShells">
                    <reactiveProperty:EventToReactiveProperty ReactiveProperty="{Binding CloseAllAboutShellClickEvent, UpdateSourceTrigger=PropertyChanged}" />
                </coreInteractivity:EventTrigger>
                <coreInteractivity:EventTrigger EventName="Click"
                                                SourceName="ReloadAboutShellMenuControl">
                    <reactiveProperty:EventToReactiveProperty ReactiveProperty="{Binding ReloadAboutShellMenuControlClickEvent, UpdateSourceTrigger=PropertyChanged}" />
                </coreInteractivity:EventTrigger>

                <!--Interactive Event Triggers for the Workflow Control Shell-->

                <coreInteractivity:EventTrigger EventName="Click"
                                                SourceName="OpenWorkflowControlShell">
                    <reactiveProperty:EventToReactiveProperty ReactiveProperty="{Binding OpenWorkflowControlClickEvent, UpdateSourceTrigger=PropertyChanged}" />
                </coreInteractivity:EventTrigger>
                <coreInteractivity:EventTrigger EventName="Click"
                                                SourceName="CloseWorkflowControlShell">
                    <reactiveProperty:EventToReactiveProperty ReactiveProperty="{Binding CloseWorkflowControlClickEvent, UpdateSourceTrigger=PropertyChanged}" />
                </coreInteractivity:EventTrigger>

                <!--Interactive Event Triggers for the Workflow Display Monitor Shell-->

                <coreInteractivity:EventTrigger EventName="Click"
                                                SourceName="OpenWorkflowDisplayMonitorShell">
                    <reactiveProperty:EventToReactiveProperty ReactiveProperty="{Binding OpenWorkflowDisplayMonitorEvent, UpdateSourceTrigger=PropertyChanged}" />
                </coreInteractivity:EventTrigger>
                <coreInteractivity:EventTrigger EventName="Click"
                                                SourceName="CloseWorkflowDisplayMonitorShell">
                    <reactiveProperty:EventToReactiveProperty ReactiveProperty="{Binding CloseWorkflowDisplayMonitorClickEvent, UpdateSourceTrigger=PropertyChanged}" />
                </coreInteractivity:EventTrigger>
            </coreInteractivity:Interaction.Triggers>

            <ig:XamMenuItem x:Name="AboutShellMenu"
                            Header="Load About Shell">
                <ig:XamMenuItem x:Name="OpenAboutShell"
                                Header="Open About Shell" />
                <ig:XamMenuItem x:Name="CloseAboutShell"
                                Header="Close About Shell" />
                <ig:XamMenuItem x:Name="CloseAllAboutShells"
                                Header="Close About Shell Stack" />
                <ig:XamMenuItem x:Name="ReloadAboutShellMenuControl"
                                Header="Reload About Shell Menu Control" />
            </ig:XamMenuItem>

            <ig:XamMenuItem x:Name="WorkflowControlMenu"
                            Header="Load Workflow Control Shell">
                <ig:XamMenuItem x:Name="OpenWorkflowControlShell"
                                Header="Open Workflow Control Shell" />
                <ig:XamMenuItem x:Name="CloseWorkflowControlShell"
                                Header="Close Workflow Control Shell" />
            </ig:XamMenuItem>

            <ig:XamMenuItem x:Name="WorkflowDisplayMonitorMenu"
                            Header="Load Workflow Display Monitor Shell">
                <ig:XamMenuItem x:Name="OpenWorkflowDisplayMonitorShell"
                                Header="Open Workflow Display Monitor Shell" />
                <ig:XamMenuItem x:Name="CloseWorkflowDisplayMonitorShell"
                                Header="Close Workflow Display Monitor Shell" />
            </ig:XamMenuItem>

        </ig:XamMenu>
    </Grid>
</UserControl>
```
Project reference.
default

No error at error list. And designer error is nothing.

**Comment by runceel** [comment]
default

**Comment by TaviTruman** [comment]
Okay then it must be something in my environment. I'll take time today to build some examples and I will re-examine my development environment. Thank you @neuecc for the time and attention to this matter; it is very much appreciated.

**Comment by TaviTruman** [comment]
Okay after some review on my end did the following and it seems to have corrected the problem.

  * I ran a repair install on Visual Studio 2015 Enterprise
  * I updated projects that use Infragistics Controls
  * Reload the base Packages for PRISM 5 + my own extensions and mods for Multiple Shells

  *Information Relative to this communication*
  * Our WPF Apps are all .NET 4.6
     * ReactiveProperty 2.3.0-pre4
     * Rx-Main 2.3.0-beta2 + Related libraries
     * Rx-WPF/XAML 2.3.0-beta2
     * PRISM 5.0

Our apps now build without error and the designers in Visual Studio and Blend detect no errors; however, I am not seeing the following errors in all projects:

  * I am not getting the Visual Designer Errors :+1: 
  * I now get this Error message: "Cannot add instance of type 'EventToReactiveProperty' to a collection of type 'TriggerActionCollection.' Only items of Type 'T' are allowed.



I am going to close this ticket out as I am no longer blocked using the Visual Designers.

**Pull request merged**
