### PR TITLE
Add syntax sugar for non generic (Async)ReactiveCommand

### PR DESCRIPTION
**Pull request by soi013**
I tried this change with the WPF sample.
Should I write a test case?

### CODE REVIEW

**Comment by runceel** [comment]
Thank you for PR!

I want to test.

**Comment by soi013** [comment]
OK, I'll try it.
Should I add to the following two?

ReactiveCommandTest
AsyncReactiveCommandTest

I have never written a test case, but I will try my best.

**Comment by soi013** [comment]
Sorry for my late Update.

**Comment by runceel** [comment]
OK! Thank you so much!

**Pull request merged**
