### PR TITLE
Delete Awaiter of IReactiveProperty<T> 

### PR DESCRIPTION
**Pull request by soi013**
This PR deletes following methods.

-  `GetAwaiter (IReactiveProperty<T>)`
- `WaitUntilValueChangedAsync (IReactiveProperty<T>)` 

Because, these methods have `IReadOnlyReactiveProperty<T>` ver.
Therefore, CS0121 is happen in following code.

```csharp
public ReactiveProperty<string> Name { get; } = new ReactiveProperty<string>("TARO");

~~~

//wait change of name in some method.
string changedName = await Name.WaitUntilValueChangedAsync();

//avoid CS0121
//string changedName = await ((IReadOnlyReactiveProperty<string>)Name).WaitUntilValueChangedAsync();
//string changedName = await (IReadOnlyReactiveProperty<string>)Name;
```

### CODE REVIEW

**Comment by runceel** [comment]
I think after merged the PR, following code would be compile error, correct?

```cs
IReactiveProperty<int> x = new ReactiveProperty<int>();
await x;
```

I guess this is a rare case.
However, I would like to be careful about breaking changes.

How do you think?

**Comment by soi013** [comment]
> And sorry for slow response.

OK. No problem.

> I would like to be careful about breaking changes.

You are right. I will cancel this PR.

Alternatively, how about adding `ReactiveProperty<T>` and `ReactivePropertySlim<T>` ver?
It`s redundant code, but dosen't have breaking changes and avoid CS0121.

```csharp

public static TaskAwaiter<T> GetAwaiter<T>(this ReactiveProperty<T> source)
~~~
public static TaskAwaiter<T> GetAwaiter<T>(this ReactivePropertySlim<T> source)
~~~
public static async Task<T> WaitUntilValueChangedAsync<T>(this ReactiveProperty<T> source, CancellationToken cancellationToken = default(CancellationToken))
~~~
public static async Task<T> WaitUntilValueChangedAsync<T>(this ReactivePropertySlim<T> source, CancellationToken cancellationToken = default(CancellationToken))

```

**Comment by runceel** [comment]
Thank you for your suggestion.
I also think it's redundant code, however I feel it's best for now.

Could you create a new PR?

**Comment by soi013** [comment]
OK. I will create new PR in next week.

**Pull request closed without merging**
