### PR TITLE
Add equalityComparer field to ReactiveProperty for compatibility with ReactivePropertySlim

### PR DESCRIPTION
**Pull request by soi013**

### CODE REVIEW

**Comment by runceel** [comment]
Thanks!

It souds good.
Could you add unit test codes and ToReactiveProperty overloads?

**Comment by soi013** [comment]
ok. I will do it.

**Comment by soi013** [comment]
I wrote tests. And all tests were passed.

But I have problems.
I suppose these are not related this pull-request.

First, I Failed to build test project.
I tried many ways.
Finally, I can build and execute tests. 
But I don't understand the key way.

**Comment by soi013** [comment]
I found solution to problem of test.
I deleted the test setting file `TraceAndTestImpact.testsettings` in `Solution Items`.

**Comment by runceel** [comment]
Thanks!!

**Comment by runceel** [comment]
I published the v4.2.0 release.

https://github.com/runceel/ReactiveProperty/releases/tag/v4.2.0

Thank you.

**Comment by soi013** [comment]
Oops! Sorry, I have not written ToReactiveProperty overload yet.
I will write it and send pull-request.

**Comment by soi013** [comment]
Oops! x2 You already have written ToReactiveProperty overload.
Thank you!

**Pull request merged**
