### PR TITLE
awaitable ReactiveProperty/ReactiveCommand

### PR DESCRIPTION
**Pull request by neuecc**
ReactiveProperty now becomes async event-model glue!
If RP is data binded, all view events can await and compose by async/await syntax.
This is the revolution of "declarative paradigm" to "async procedural paradigm".

> Note: This behaviour is breaking changes, default `await IObservable<T>` is await **last** value but this is like await **first** value.

### CODE REVIEW

**Comment by runceel** [comment]
Your code break existing codes.

For example:
```cs
// Compile error!
// error CS0234: The type or namespace name 'FromObject' does not exist in the namespace 'ReactiveProperty' (are you missing an assembly reference?)
var rp = ReactiveProperty.FromObject(x);
```

The cause of the error is namespace of CompletionHelper class.
```cs
namespace ReactiveProperty.Internals // why ReactiveProperty namespace?
{
    internal static class CompletionHelper
    {
        public static void AppendContinuation(ref object continuationField, Action newContinuation)
```

Could you fix this error?

**Comment by neuecc** [comment]
Oh, sorry!
I've fixed and changed default project namespace to `Reactive.Bindings`

```
-    <RootNamespace>ReactiveProperty</RootNamespace>
+    <RootNamespace>Reactive.Bindings</RootNamespace>
```
```

**Comment by runceel** [comment]
Thank you for fixing and changing default project namespace.
I forgot to change default project namespace setting.

**Comment by neuecc** [comment]
sorry, I'm rethinking API.
I'll change API in a few days.

**Comment by runceel** [comment]
OK.

**Comment by neuecc** [comment]
fix `ReactivePropertyAwaiter` (continuation trampolined itself)
rename `ToTask` -> `WaitUntilValueChangedAsync`

**Comment by runceel** [comment]
Thank you for implementing great feature.
Because the concern of this code is high performance, the code is very difficult for me .

In this PR, there are two test cases.
Is that enough test cases for this feature?
I'll merge the PR after checking coverage of test cases .

**Comment by runceel** [comment]
Hi @neuecc ,
Thank you for the pull request.
I've checked.
And I added two tests for case of type of the `continuation` field is `Queue<Action>`.

**Comment by neuecc** [comment]
sorry for no testcase and usage.
thanks, pretty good!

**Pull request merged**
