### PR TITLE
Add ReactiveProperty.Create methods

### PR DESCRIPTION
**Pull request by vain0**
I want static method version of constructors. They are useful alternatives to constructors because C# can infer type parameters of static methods.

### CODE REVIEW

**Comment by xin9le** [comment]
Thank you for your PR.

In our 1st impression, we thing your suggestion is nice. We might not write generic type '<T>'. But then again, when we type '= new ' on Visual Studio, its intellisense suggest 'new ReactiveProperty<T>'. This is very useful, therefore we don't know your suggestion's advantages.

Could you tell us what your advantages?

**Comment by vain0** [comment]
``ReactiveProperty.Create`` methods have two advantages.

1\. ``= new`` + code completion works only when we write new code. When we changes the inner type, we must fix the type parameter of constructor too.

```csharp
ReactiveProperty<int> P { get; } = new ReactiveProperty<int>();

↓

ReactiveProperty<long> P { get; } = new ReactiveProperty<long>();
```

2\. They works fine with `var`.

```csharp
// No need to repeat the type of x.
var p = ReactiveProperty.Create(x);
```

**Comment by musakasim** [comment]
When you really need to use reactive property as a variable? I can only imagine that it would be helpful in a test method. and wouldn't you want that your test mehods to be as declerative as possible

**Comment by runceel** [comment]
I think that this feature have the little benefit.
But this feature provide confuse to user.
Which should I use?? constructor? factory method?

I hope that ReactiveProperty keep simple.
Sorry, I reject this pull request.

**Comment by vain0** [comment]
I see. Thank you for your response anyway.

**Comment by runceel** [comment]
@vain0 Thank you.
I am looking foward to other PR.

**Pull request closed without merging**
